aws:
  region: eu-north-1

  bucket:
    input: upload-s3-bucket-18032026
    encrypted: encrypt-s3-bucket-18032026
    decrypted: decrypt-s3-bucket-18032026

  kms:
    key: alias/json-encryption-key