aws:
  region: ap-south-1

  bucket:
    input: upload-s3-bucket-18032026-1
    encrypted: encrypt-s3-bucket-18032026-1
    decrypted: decrypt-s3-bucket-18032026-1

  kms:
    key: alias/ecrypt-decrypt-json-kms